In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns   
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [4]:
#data information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

In [6]:
df.describe()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,84.131700,6.470100,3.042000,5.438000,69.601500
std,2.3081,1.46889,1.172422,1.075118,9.399246,1.226377,2.025423,2.847501,16.888564
min,17.0000,0.00000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.7500,2.60000,1.700000,1.000000,78.000000,5.600000,1.000000,3.000000,58.475000
50%,20.0000,3.50000,2.500000,1.800000,84.400000,6.500000,3.000000,5.000000,70.500000
75%,23.0000,4.50000,3.300000,2.525000,91.025000,7.300000,5.000000,8.000000,81.325000
max,24.0000,8.30000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

In [7]:
#checking missing values
df.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isna().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [ ]:
df.describe(include='object')

,student_id,gender,part_time_job,diet_quality,parental_education_level,internet_quality,extracurricular_participation
count,909,909,909,909,909,909,909
unique,909,3,2,3,3,3,2
top,S1000,Male,No,Fair,High School,Good,No
freq,1,440,713,396,392,410,620

In [11]:
df.describe(include='object').columns

Index(['student_id', 'gender', 'part_time_job', 'diet_quality',
       'parental_education_level', 'internet_quality',
       'extracurricular_participation'],
      dtype='object')

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [15]:
object_cols = df.select_dtypes(include="object").columns

for col in object_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [16]:
df

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,s1000,23,female,0.0,1.2,1.1,no,85.0,8.0,fair,6,master,average,8,yes,56.2
1,s1001,20,female,6.9,2.8,2.3,no,97.3,4.6,good,6,high school,average,8,no,100.0
2,s1002,21,male,1.4,3.1,1.3,no,94.8,8.0,poor,1,high school,poor,1,no,34.3
3,s1003,23,female,1.0,3.9,1.0,no,71.0,9.2,poor,4,master,good,1,yes,26.8
4,s1004,19,female,5.0,4.4,0.5,no,90.9,4.9,fair,3,master,good,1,no,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,s1995,21,female,2.6,0.5,1.6,no,77.0,7.5,fair,2,high school,good,6,yes,76.1
996,s1996,17,female,2.9,1.0,2.4,yes,86.0,6.8,poor,1,high school,average,6,yes,65.9
997,s1997,20,male,3.0,2.6,1.3,no,61.9,6.5,good,5,bachelor,good,9,yes,64.4
998,s1998,24,male,5.4,4.1,1.1,yes,100.0,7.6,fair,0,bachelor,average,1,no,69.7
999,s1999,19,female,4.3,2.9,1.9,no,89.4,7.1,good,2,bachelor,average,8,no,74.9

In [18]:
df['gender'].value_counts()

gender
male      440
female    433
other      36
Name: count, dtype: int64

In [19]:
#Removing "Others" from gender

df = df[df["gender"] != "other"]

In [20]:
df["gender"].value_counts()

gender
male      440
female    433
Name: count, dtype: int64

In [21]:
df.shape

(873, 16)

In [24]:
df['age'].describe()

count    873.000000
mean      20.465063
std        2.304061
min       17.000000
25%       18.000000
50%       20.000000
75%       22.000000
max       24.000000
Name: age, dtype: float64

In [25]:
df["parental_education_level"].value_counts()

parental_education_level
high school    371
bachelor       342
master         160
Name: count, dtype: int64

In [38]:
hour_cols = [
    "study_hours_per_day",
    "social_media_hours",
    "netflix_hours",
    "sleep_hours"
]

for col in hour_cols:
    df[col] = df[col].clip(lower=0, upper=24)

df[hour_cols].describe()

C:\Users\CSP\AppData\Local\Temp\ipykernel_884\4151872362.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower=0, upper=24)
C:\Users\CSP\AppData\Local\Temp\ipykernel_884\4151872362.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower=0, upper=24)
C:\Users\CSP\AppData\Local\Temp\ipykernel_884\4151872362.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower=0, upper=24)
C:\Users\CSP\AppData\Local\Temp\ipykernel_884\4151872362.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower=0, upper=24)

       study_hours_per_day  social_media_hours  netflix_hours  sleep_hours
count           873.000000          873.000000     873.000000   873.000000
mean              3.531844            2.498855       1.820733     6.462314
std               1.485679            1.162644       1.058287     1.229189
min               0.000000            0.000000       0.000000     3.200000
25%               2.500000            1.700000       1.000000     5.600000
50%               3.500000            2.500000       1.800000     6.400000
75%               4.500000            3.300000       2.500000     7.300000
max               8.300000            7.200000       5.400000    10.000000

In [39]:
df["attendance_percentage"].describe()

count    873.000000
mean      83.879152
std        9.432564
min       56.000000
25%       77.500000
50%       84.300000
75%       90.700000
max      100.000000
Name: attendance_percentage, dtype: float64

In [40]:
df['exam_score'].describe()

count    873.000000
mean      69.470332
std       17.042099
min       18.400000
25%       58.400000
50%       70.500000
75%       81.500000
max      100.000000
Name: exam_score, dtype: float64

In [41]:
df['mental_health_rating'].describe()

count    873.000000
mean       5.466208
std        2.861732
min        1.000000
25%        3.000000
50%        5.000000
75%        8.000000
max       10.000000
Name: mental_health_rating, dtype: float64

In [42]:
df.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [43]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 873 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     873 non-null    object
 1   age                            873 non-null    int64
 2   gender                         873 non-null    object
 3   study_hours_per_day            873 non-null    float64
 4   social_media_hours             873 non-null    float64
 5   netflix_hours                  873 non-null    float64
 6   part_time_job                  873 non-null    object
 7   attendance_percentage          873 non-null    float64
 8   sleep_hours                    873 non-null    float64
 9   diet_quality                   873 non-null    object
 10  exercise_frequency             873 non-null    int64
 11  parental_education_level       873 non-null    object
 12  internet_quality               873 non-null    object
 13  mental_health_rating           873 non-null    int64
 14  extracurricular_participation  873 non-null    object
 15  exam_score                     873 non-null    float64
dtypes: float64(6), int64(3), object(7)
memory usage: 115.9+ KB

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,873.000000,873.000000,873.000000,873.000000,873.000000,873.000000,873.000000,873.000000,873.000000
mean,20.465063,3.531844,2.498855,1.820733,83.879152,6.462314,3.051546,5.466208,69.470332
std,2.304061,1.485679,1.162644,1.058287,9.432564,1.229189,2.034305,2.861732,17.042099
min,17.000000,0.000000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.000000,2.500000,1.700000,1.000000,77.500000,5.600000,1.000000,3.000000,58.400000
50%,20.000000,3.500000,2.500000,1.800000,84.300000,6.400000,3.000000,5.000000,70.500000
75%,22.000000,4.500000,3.300000,2.500000,90.700000,7.300000,5.000000,8.000000,81.500000
max,24.000000,8.300000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

In [45]:
df.drop(columns=["student_id"], inplace=True)

C:\Users\CSP\AppData\Local\Temp\ipykernel_884\1443768791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["student_id"], inplace=True)

In [46]:
df

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,23,female,0.0,1.2,1.1,no,85.0,8.0,fair,6,master,average,8,yes,56.2
1,20,female,6.9,2.8,2.3,no,97.3,4.6,good,6,high school,average,8,no,100.0
2,21,male,1.4,3.1,1.3,no,94.8,8.0,poor,1,high school,poor,1,no,34.3
3,23,female,1.0,3.9,1.0,no,71.0,9.2,poor,4,master,good,1,yes,26.8
4,19,female,5.0,4.4,0.5,no,90.9,4.9,fair,3,master,good,1,no,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,female,2.6,0.5,1.6,no,77.0,7.5,fair,2,high school,good,6,yes,76.1
996,17,female,2.9,1.0,2.4,yes,86.0,6.8,poor,1,high school,average,6,yes,65.9
997,20,male,3.0,2.6,1.3,no,61.9,6.5,good,5,bachelor,good,9,yes,64.4
998,24,male,5.4,4.1,1.1,yes,100.0,7.6,fair,0,bachelor,average,1,no,69.7
999,19,female,4.3,2.9,1.9,no,89.4,7.1,good,2,bachelor,average,8,no,74.9

In [50]:
df["extracurricular_participation"].value_counts()

extracurricular_participation
no     597
yes    276
Name: count, dtype: int64

In [51]:
#saving cleaned data
df.to_csv('cleaned_data.csv', index=False)